### ISSUE TITLE
Allow run only relaychain without any parachains

### ISSUE THREAD

**Issue by GopherJ** [open-web3-stack/parachain-launch#12]
sometimes for test purpose, it can be good to run only relaychain testnet then add parachain later through extrinsics.

**Comment by bingryan** [comment]
@GopherJ 
I think, this purpose can also be implemented now. before running the following code, delete  the container of the parachains logic  from `docker-compose.yml`.

```
docker-compose up -d --build
```

**Comment by xlc** [comment]
empty parachains should just work right?

**Comment by bingryan** [comment]
can't work right now.

**Comment by xlc** [comment]
what's the issue? you can fix whatever the issue is instead of adding new flags?
