### ISSUE TITLE
support parachain which doesn't have key command

### ISSUE THREAD

**Issue by GopherJ** [open-web3-stack/parachain-launch#13]
statemine doesn't have key command,  since we only use key command for node-key generation, maybe we can use other chains instead of the parachain itself.

**Comment by GopherJ** [comment]
now statemine has key command so this can be closed

**Comment by dutterbutter** [comment]
Is there any future support for this? I am trying to use the tool right now and unfortunately cannot due to this limitation. 

`parachain-launch` is an awesome tool and it would be great to support parachains which don't have `key` command.

**Comment by xlc** [comment]
It is possible to generate keys without using the key subcommand it but it is really the parachain node should be fixed.

But I don't mind contributions on remove the dependency on key subcommand.
