### ISSUE TITLE
Running polkadot 110 but chain at 9430 ? 

### ISSUE THREAD

**Issue by goncer** [open-web3-stack/parachain-launch#187]
Hi! 
When running one of the examples ( ie [relayChain](https://github.com/open-web3-stack/parachain-launch/blob/master/configs/relaychain-only.yml )  ) 
Evth goes fine, but when checking the relay-state, it prints  94.3.0
From rococo I can see that
specVersion: 1,006,002
But locally I would expect 1,001,000
but  getting 9430 on rpc -> getRuntimeVersion
```
{
  specName: rococo
  implName: parity-rococo-v2.0
  authoringVersion: 0
  specVersion: 9,430
  implVersion: 0
``` 
Relay dockerFile seems to be fine: 
```
 cat relaychain.Dockerfile                                                                                   ✔ 
FROM parity/polkadot:v1.1.0
COPY . /app%                                                                            
``` 
And the image seems to be fine too 

```
 docker run -it --entrypoint=/bin/bash parity/polkadot:v1.1.0                                           
parity@4621751af236:/$ /usr/bin/polkadot --version
polkadot 1.1.0-f60318f6868
```

![image](https://github.com/open-web3-stack/parachain-launch/assets/15139384/9c2ead4b-c912-44e2-ac1c-9ecefaf223d2)

running 2.0 version : 
 npx @open-web3/parachain-launch  --version --> 2.0.0

How to reproduce:

1. rm -rf output ;  npx @open-web3/parachain-launch generate acala.yml --yes
2. cd output ; docker compose up -d --build
3. go to : https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/ 
4. Check that runtime version is not 110 on rpc-> state > getRuntimeVersion

Thankss!!

**Comment by xlc** [comment]
you need to edit the config to use a recent version of the relaychain image

**Comment by goncer** [comment]
Thanks for the answer @xlc ! 
somehow I expected that 1.10 matches with that runtime version :shrug: 

I updated to 1.3.0 and seems to be ok, rococo/103000

Note that from 1.4.0 parachain-launch fails on building the spec: 
```
npx @open-web3/parachain-launch generate config.yml --yes
$ docker run --rm mangatasolutions/mangata-node:develop-fast build-spec --chain=mangata-rococo-local --disable-default-bootnode > /tmp/mangata-rococo-local-2024-02-02.json
$ docker run --rm parity/polkadot:v1.4.0 build-spec --chain=rococo-local --disable-default-bootnode > /tmp/rococo-local-2024-02-02.json
Trace: Error: TypeError: Cannot read properties of undefined (reading 'runtime_genesis_config')
    at generateRelaychainGenesisFile (/home/goncer/.npm/_npx/76f5f9e61c1b2e31/node_modules/@open-web3/parachain-launch/lib/index.js:167:33)
    at generate (/home/goncer/.npm/_npx/76f5f9e61c1b2e31/node_modules/@open-web3/parachain-launch/lib/index.js:411:5)
    at fatal (/home/goncer/.npm/_npx/76f5f9e61c1b2e31/node_modules/@open-web3/parachain-launch/lib/index.js:79:13)
``` 
Most prob because the migration mentioned here: 

https://substrate.stackexchange.com/questions/10655/build-fast-runtime-for-kusama-on-polkadotsdk

If you know any suitable docker image to use as relay above 1.3.0 I would really appreciate :) 
Br,
Gonzalo.

**Comment by goncer** [comment]
not a prachain-launch issue! my bad :pray:
