### ISSUE TITLE
nextFreeId seems wrong. still 2000.

### ISSUE THREAD

**Issue by saintfeng** [open-web3-stack/parachain-launch#2]
I've deployed the system. 
When I want to reserve a ParaId via the **Polkadot Apps UI under the Parachains -> Parathreads tab, + ParaID button**,
it pops out the default ParaId for me to reserve is still 2000, which is already taken by karura. so I got stuck here. 

According to this explanation, "The Id of this parachain as known on the network (selected from nextFreeId)", I believe that nextFreeId on the network seems wrong.

Thx.

**Comment by xlc** [comment]
This is a polkadot issue please report there. There are no way to config next free ID in genesis. 
But you can just remove Karura from config or replace it with your parachain.
