### ISSUE TITLE
Error: Input("Error parsing spec file: unknown field `paraId` at line 239 column 1")

### ISSUE THREAD

**Issue by bingryan** [open-web3-stack/parachain-launch#21]
hello, update to polkadot:v0.9.13.  i get some error with this update:

https://github.com/open-web3-stack/parachain-launch/blob/0a1ff0f3330255b469022dc7cbb394b0f34d1994/src/index.ts#L311

**Comment by bingryan** [comment]
use `para_id`?
```
spec.para_id = id; 
```

**Comment by xlc** [comment]
All the other keys is camel case so we are using `paraId` but I just found out statemine is using `para_id`.

So it should just detect which one was used and update that accordingly
