### ISSUE TITLE
trying to interact with polkadot.js

### ISSUE THREAD

**Issue by 0xmostima** [open-web3-stack/parachain-launch#25]
When I start the relay chains & the parachains locally and tried to interact via polkadot.js through e.g. `ws://0.0.0.0:30333`, the UI is stuck at initialization. Is there additional configuration I should do to make this work? I'm using the default configuration with Acala. Thanks!

**Comment by xlc** [comment]
You are connecting to the wrong port. It will be 9944 or one of the 994x port.

**Comment by 0xmostima** [comment]
thank you!
