### ISSUE TITLE
support balance >= 1e21

### ISSUE THREAD

**Issue by GopherJ** [open-web3-stack/parachain-launch#9]
currently parachain-launch will not be able to support balance >= 1e21 due to JS behaviour:

```
console.log(JSON.stringify(10 ** 20)) // 100000000000000000000

console.log(JSON.stringify(10 ** 21)) // 1e+21
```

serde_json can parse `100000000000000000000` but not `1e+21`, which means if we have a balance bigger than 1e21 then parachain-launch will create invalid chainspec json (which cannot be imported by serde_json)

**Comment by GopherJ** [comment]
maybe we can use: https://github.com/sidorares/json-bigint

**Comment by GopherJ** [comment]
Ref: https://github.com/serde-rs/json/issues/774

**Comment by xlc** [comment]
I think we can just save it as string instead of number and should work.

**Comment by GopherJ** [comment]
I think we can do something like: https://dev.to/benlesh/bigint-and-json-stringify-json-parse-2m8p

**Comment by xlc** [comment]
Yes that should work. Should also start using bigint everywhere instead of number
